### ISSUE TITLE
Cannot install the package in Julia 1.5

### ISSUE THREAD

**Issue by tiagoseq** [tungli/Findpeaks.jl#5]
Hello, I was trying to install the package and got this error message:
ERROR: The following package names could not be resolved: * Findpeaks (not found in project, manifest or registry)

**Comment by tungli** [comment]
How did you try to install it? This package is not registered (see [here](https://github.com/tungli/Findpeaks.jl/issues/3#issuecomment-735408714)).

**Comment by tiagoseq** [comment]
I tried to install it like this:
`using Pkg`
`Pkg.add("Findpeaks")`

So for what I read in that post, is that this package was moved to `DSP.jl`?

Thanks!

**Comment by tungli** [comment]
I have a [pull request to DSP.jl](https://github.com/JuliaDSP/DSP.jl/pull/369) open but I am not sure if it will get accepted and in what form and when.

In the meantime this should work:

```julia
using Pkg
Pkg.add(url="https://github.com/tungli/Findpeaks.jl")
```
